# Use the LB-IPAM functionality of cilium, it announces via ARP the IP addresses of the LBs on the local network
# https://docs.cilium.io/en/stable/network/lb-ipam/
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
spec:
  blocks:
    - start: "192.168.10.30"
      stop: "192.168.10.39"
