apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
spec:
  project: default
  sources:
    - chart: traefik
      repoURL: ghcr.io/traefik/helm
      targetRevision: 36.2.0
      helm:
        valueFiles:
          - '$values/infrastructure/traefik/values.yaml'
    - repoURL: https://github.com/riemervdzee/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
