apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "argocd.homelab.riemer.dev"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
