apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.28.3
      helm: {}
#        valueFiles:
#          - '$values/gitops/rook-ceph/files/rook-operator-values.yaml'
    - repoURL: https://github.com/riemervdzee/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
      - ServerSideApply=true
