apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/riemervdzee/homelab.git
    targetRevision: HEAD
    path: gitops/_argocd_app_bootstrap
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
